AWSTemplateFormatVersion: '2010-09-09'
Description: "Deploy TaasApi Resources"

Parameters:
  GlueJobScriptBucket:
    Description: Name of the script bucket
    Type: String
  ApplicationName:
    Description: Application
    Type: String
  slackEmail:
    Description: Slack Email address 
    Type: String
  orgEmail:
    Description: Org Email address 
    Type: String
  iamRoleName:
    Description: IAM Role Name
    Type: String
  snsTopicName:
    Description: IAM Role Name
    Type: String
  firstLambdaName:
    Description: First Lambda Name
    Type: String
  secondLambdaName:
    Description: Second Lambda Name
    Type: String
  thirdLambdaName:
    Description: Third Lambda Name
    Type: String
  firstConnectSubnet:
    Description: Subnet
    Type: String
  firstConnectsg:
    Description: sg1
    Type: String
  secondConnectsg:
    Description: sg2
    Type: String

Resources:
  #SNS Topic
  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Keysight Test Enginee Notification
      TopicName: !Ref snsTopicName
      Subscription:
        - Protocol: email
          Endpoint: !Ref slackEmail
        - Protocol: email
          Endpoint: !Ref orgEmail

  ResponseLambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn: MyLambdaExecutionRole

    Properties:
      Description: Returns Response to ALB
      FunctionName: !Ref firstLambdaName
      Code:
        S3Bucket: !Sub ${GlueJobScriptBucket}
        S3Key: !Sub "${ApplicationName}/glue/script/lambda-zips/response_function.zip"
      Handler: lambda_function.lambda_handler
      Role: !GetAtt MyLambdaExecutionRole.Arn
      Runtime: python3.8
      Timeout: 60
      Layers:
        - !Ref TaasJiraLayer

  ConnectLambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn: MyLambdaExecutionRole

    Properties:
      Description: Connects to EC2
      FunctionName: !Ref secondLambdaName
      Code:
        S3Bucket: !Sub ${GlueJobScriptBucket}
        S3Key: !Sub "${ApplicationName}/glue/script/lambda-zips/connect_function.zip"
      Handler: lambda_function.lambda_handler
      Role: !GetAtt MyLambdaExecutionRole.Arn
      Runtime: python3.8
      Timeout: 60
      Layers:
        - !Ref TaasJiraLayer
      VpcConfig:
        SecurityGroupIds:
          - !Ref firstConnectsg
          - !Ref secondConnectsg
        SubnetIds:
          - !Ref firstConnectSubnet

  UpdateLambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn: MyLambdaExecutionRole

    Properties:
      Description: Updates the Jira
      FunctionName: !Ref thirdLambdaName
      Code:
        S3Bucket: !Sub ${GlueJobScriptBucket}
        S3Key: !Sub "${ApplicationName}/glue/script/lambda-zips/update_function.zip"
      Handler: lambda_function.lambda_handler
      Role: !GetAtt MyLambdaExecutionRole.Arn
      Runtime: python3.8
      Timeout: 60
      Layers:
        - !Ref TaasJiraLayer
   
  MyLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref iamRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess

      Policies:
        - PolicyName: LambdaVpcAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                Resource: "*"
  TaasJiraLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket: taasapi-saas-poc
        S3Key: layer/JiraLayer.zip
      CompatibleRuntimes:
        - python3.8