AWSTemplateFormatVersion: '2010-09-09'
Description: "Deploy TaasApi Resources"

Parameters:
  secondLambdaName:
    Description: Second Lambda Name
    Type: String

  firstConnectSubnet:
    Description: Subnet
    Type: String
  firstConnectsg:
    Description: sg1
    Type: String
  secondConnectsg:
    Description: sg2
    Type: String

Resources:

  ConnectLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Connects to EC2
      FunctionName: !Ref secondLambdaName
      Code:
        ZipFile: |
          import json
    
          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello from Lambda!')
              }
      Handler: index.lambda_handler
      Role: arn:aws:iam::968504157731:role/5g-defender-automation-role
      Runtime: python3.8
      Timeout: 60
      VpcConfig:
        SecurityGroupIds:
          - !Ref firstConnectsg
          - !Ref secondConnectsg
        SubnetIds:
          - !Ref firstConnectSubnet
